# Generated by Django 3.1.3 on 2020-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Crypto Blog', max_length=20),
        ),
    ]
