# Generated by Django 3.1.3 on 2020-12-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0006_auto_20201208_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='does not matter', max_length=200),
        ),
    ]
